#ifndef SCREEN_CONFIG_H
#define SCREEN_CONFIG_H

#include <stdint.h>

#define SCREEN_PAGE_GOOGLE     0
#define SCREEN_PAGE_INSTAGRAM  1

#define SCREEN_GOOGLE_QR_MAX_BYTES      300U
#define SCREEN_INSTAGRAM_QR_MAX_BYTES   300U
#define SCREEN_DGUS_QR_UART_MAX_PER_FRAME 250U

#define SCREEN_TOPIC_LEAF_TEST_GMB  "test-gmb"
#define SCREEN_TOPIC_LEAF_GMB       "gmb"
#define SCREEN_TOPIC_LEAF_INSTAGRAM "instagram"

#define SCREEN_VP_GOOGLE_RATING_TENTHS        0x300AU
#define SCREEN_VP_GOOGLE_RATING_DOT             0x300CU
#define SCREEN_VP_GOOGLE_RATING_DECIMAL         0x300EU
#define SCREEN_VP_GOOGLE_VERIFIED_REVIEWS_100   0x301AU
#define SCREEN_VP_GOOGLE_VERIFIED_REVIEWS_10    0x301CU
#define SCREEN_VP_GOOGLE_VERIFIED_REVIEWS_1     0x301EU
#define SCREEN_VP_GOOGLE_REMAIN_GOAL            0x3020U
#define SCREEN_VP_GOOGLE_NEXT_GOAL_100          0x3022U
#define SCREEN_VP_GOOGLE_NEXT_GOAL_10           0x3024U
#define SCREEN_VP_GOOGLE_NEXT_GOAL_1            0x3026U
#define SCREEN_VP_GOOGLE_PROGRESS_BAR           0x3028U
#define SCREEN_VP_GOOGLE_QR                     0x3080U

#define SCREEN_VP_INSTAGRAM_FOLLOWERS_100000    0x3500U
#define SCREEN_VP_INSTAGRAM_FOLLOWERS_10000     0x3502U
#define SCREEN_VP_INSTAGRAM_FOLLOWERS_1000      0x3504U
#define SCREEN_VP_INSTAGRAM_FOLLOWERS_100       0x3506U
#define SCREEN_VP_INSTAGRAM_FOLLOWERS_10        0x3508U
#define SCREEN_VP_INSTAGRAM_FOLLOWERS_1         0x350AU
#define SCREEN_VP_INSTAGRAM_PROGRESS_BAR        0x3520U
#define SCREEN_VP_INSTAGRAM_REMAIN_GOAL_10      0x3522U
#define SCREEN_VP_INSTAGRAM_REMAIN_GOAL_1       0x3524U
#define SCREEN_VP_INSTAGRAM_ACHIEVEMENTS_100000 0x3526U
#define SCREEN_VP_INSTAGRAM_ACHIEVEMENTS_10000  0x3528U
#define SCREEN_VP_INSTAGRAM_ACHIEVEMENTS_1000   0x352AU
#define SCREEN_VP_INSTAGRAM_ACHIEVEMENTS_100    0x352CU
#define SCREEN_VP_INSTAGRAM_ACHIEVEMENTS_10       0x352EU
#define SCREEN_VP_INSTAGRAM_ACHIEVEMENTS_1      0x3530U
#define SCREEN_VP_INSTAGRAM_QR                  0x3700U

#define SCREEN_JSON_BUF_SIZE 4096

#endif /* SCREEN_CONFIG_H */
